name: Container Security Analysis

on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  REGISTRY: docker.io
  IMAGE_NAME: joseco/agri-yura
  TRIVY_CACHE_DIR: /tmp/trivy-cache

jobs:
  build-scan-push:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      security-events: write
    outputs:
      tag: ${{ steps.define_tag.outputs.tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Define TAG
      id: define_tag
      run: |
        TAG="${{ github.run_number }}.${{ github.ref_name }}"
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Build Image (load into local Docker)
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
        push: false
        load: true
    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
        format: 'sarif'
        exit-code: 0
        severity: 'CRITICAL,HIGH'
        output: 'trivy-results.sarif'
 
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
          sarif_file: 'trivy-results.sarif'
    
    # - name: Scan image with Trivy (SARIF)
    #   run: |
    #     docker run --rm \
    #       -v /var/run/docker.sock:/var/run/docker.sock \
    #       -v ${{ env.TMP_DIR }}:/output \
    #       aquasec/trivy:0.68.1 image \
    #         --severity HIGH,CRITICAL \
    #         --ignore-unfixed \
    #         --format sarif \
    #         --output /output/trivy.sarif \
    #         ${{ env.IMAGE_NAME }}:${{ env.TAG }}
    
    # - name: Upload Trivy Results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: trivy-scan
    #     path: ${{ env.TMP_DIR }}
    # - name: Upload SARIF to GitHub Security
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: ${{ env.TMP_DIR }}/trivy.sarif
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Push image (only if scan passed)
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
        push: true

  deploy:
    runs-on: [self-hosted]
    needs: build-scan-push
    steps:
    - name: Stop previous services
      run: docker compose down -v || true

    - name: Start new version
      run: |
        export TAG=${{ needs.build-scan-push.outputs.tag }}
        docker compose -f docker-compose.yml up -d

    - name: Verify landing page
      run: curl -I https://yuravision.tech