name: Deploy with Docker Compose

on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  REGISTRY: docker.io
  IMAGE_NAME: joseco/agri-yura

jobs:
  build-scan-push:
    runs-on: [self-hosted]
    permissions:
      contents: read
    outputs:
      tag: ${{ steps.define_tag.outputs.tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Define TAG
      id: define_tag
      run: |
        TAG="${{ github.run_number }}.${{ github.ref_name }}"
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Build Image (load into local Docker)
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
        push: false
        load: true
    
    - name: Prepare Trivy temp directory
      run: |
        mkdir -p trivy-tmp
        echo "UID=$(id -u)" >> $GITHUB_ENV
        echo "GID=$(id -g)" >> $GITHUB_ENV
        curl -sSL -o trivy-tmp/junit.tpl \
          https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl
        echo "TMP_DIR=$(pwd)/trivy-tmp" >> $GITHUB_ENV
    
    - name: Scan image with Trivy
      run: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v ${{ env.TMP_DIR }}:/output \
          aquasec/trivy:0.68.1 image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --format template \
            --template "@/output/junit.tpl" \
            --output /output/trivy_junit.xml \
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
    
    - name: Upload Trivy Results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan
        path: ${{ env.TMP_DIR }}

    - name: Publish Trivy Scan Results
      uses: dorny/test-reporter@v1
      with:
        name: Trivy Scan
        path: $TMP/trivy_junit.xml
        reporter: java-junit


    - name: Push image (only if scan passed)
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
        push: true

  deploy:
    runs-on: [self-hosted]
    needs: build-scan-push
    steps:
    - name: Stop previous services
      run: docker compose down -v || true

    - name: Start new version
      run: |
        export TAG=${{ needs.build-scan-push.outputs.tag }}
        docker compose -f docker-compose.yml up -d

    - name: Verify landing page
      run: curl -I https://yuravision.tech